---
driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: debian-jessie
    driver_config:
      run_command: /sbin/init

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: ndenv
  state_top:
    base:
      '*':
        - ndenv

suites:
  #- name: default
  - name: version-7.3.0
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - ndenv
        ndenv.sls:
          ndenv:
            users:
              root:
                user: root
                group: root
                node:
                  global: 7.3.0
                  packages_install_options: ''
                  packages:
                    - grunt
                    - gulp
                  versions:
                    - 7.3.0

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
